<?php
/**
 * Renders the `[doublescale_booking]` shortcode.
 *
 * The shortcode does not render the booking form inline — it embeds the
 * standalone booking page that {@see BookingFrontendHandler} already serves at
 * `?doublescale_booking_event=<slug>`, so the shortcode, the Direct Link, the
 * Embed Code and the QR Code in the admin Share modal all resolve to one route.
 *
 * @package DoubleScale
 */

namespace DoubleScale\Modules\Booking\Renderer;

defined( 'ABSPATH' ) || exit;

use DoubleScale\Modules\Booking\Models\EventModel;

/**
 * Booking shortcode handler.
 */
class BookingShortcode {

	/**
	 * Shortcode tag. Matches the tag generated by the admin Share modal.
	 *
	 * @var string
	 */
	public const SHORTCODE_NAME = 'doublescale_booking';

	/**
	 * @var string
	 */
	private const SHORTCODE = self::SHORTCODE_NAME;

	/**
	 * Fallback minimum height when neither `min_height` nor `height` is given.
	 *
	 * @var string
	 */
	private const DEFAULT_MIN_HEIGHT = '500px';

	/**
	 * Event model class name (injectable for tests).
	 *
	 * @var string
	 */
	private string $event_model_class;

	/**
	 * @param string $event_model_class Event model class name.
	 */
	public function __construct( string $event_model_class = EventModel::class ) {
		$this->event_model_class = $event_model_class;

		add_shortcode( self::SHORTCODE, array( $this, 'render_shortcode' ) );
	}

	/**
	 * Render the shortcode.
	 *
	 * @param array<string, string>|string $atts Shortcode attributes.
	 * @return string
	 */
	public function render_shortcode( $atts ): string {
		$atts = shortcode_atts(
			array(
				'id'         => null,
				'width'      => '100%',
				'min_height' => null,
				'max_height' => null,
				'height'     => null,
			),
			(array) $atts,
			self::SHORTCODE
		);

		$id = (int) $atts['id'];
		if ( $id <= 0 ) {
			return esc_html__( 'Invalid event ID.', 'doublescale' );
		}

		$event = $this->event_model_class::find( $id );
		if ( ! $event || empty( $event->slug ) ) {
			return esc_html__( 'Event not found.', 'doublescale' );
		}

		list( $width, $min_height, $max_height ) = $this->parse_dimensions( $atts );

		$src = home_url( '/?doublescale_booking_event=' . rawurlencode( (string) $event->slug ) );

		return sprintf(
			'<iframe class="doublescale-booking-iframe" src="%s" title="%s" loading="lazy" style="border:0;display:block;width:%s;min-height:%s;max-height:%s"></iframe>',
			esc_url( $src ),
			esc_attr__( 'Booking form', 'doublescale' ),
			esc_attr( $width ),
			esc_attr( $min_height ),
			esc_attr( $max_height )
		);
	}

	/**
	 * Resolve the width / min-height / max-height CSS values.
	 *
	 * `height` is a legacy alias honoured only when `min_height` is absent.
	 * A width of `auto` collapses an iframe to its intrinsic 300px, so it is
	 * treated as "full width" instead.
	 *
	 * @param array<string, string|null> $atts Parsed shortcode attributes.
	 * @return array{0: string, 1: string, 2: string}
	 */
	private function parse_dimensions( array $atts ): array {
		$width = $this->sanitize_dimension( $atts['width'], '100%' );
		if ( 'auto' === strtolower( $width ) ) {
			$width = '100%';
		}

		$min_height = $this->sanitize_dimension( $atts['min_height'], '' );
		if ( '' === $min_height ) {
			$min_height = $this->sanitize_dimension( $atts['height'], self::DEFAULT_MIN_HEIGHT );
		}

		$max_height = $this->sanitize_dimension( $atts['max_height'], 'auto' );

		return array( $width, $min_height, $max_height );
	}

	/**
	 * Validate a CSS length so shortcode attributes cannot inject declarations
	 * into the inline `style`. Bare numbers are treated as pixels.
	 *
	 * @param string|null $value    Raw attribute value.
	 * @param string      $fallback Value used when $value is empty or invalid.
	 * @return string
	 */
	private function sanitize_dimension( $value, string $fallback ): string {
		$value = trim( (string) $value );

		if ( '' === $value ) {
			return $fallback;
		}

		if ( preg_match( '/^auto$/i', $value ) ) {
			return 'auto';
		}

		if ( preg_match( '/^(\d+(?:\.\d+)?)(px|%|em|rem|vh|vw)?$/i', $value, $matches ) ) {
			$unit = isset( $matches[2] ) && '' !== $matches[2] ? strtolower( $matches[2] ) : 'px';
			return $matches[1] . $unit;
		}

		return $fallback;
	}
}
