<?php
/**
 * Add recurrence_id column to invoices.
 *
 * Links an invoice generated by the Pro recurring-invoice engine back to the
 * recurrence rule that spawned it. Deliberately NOT reusing `subscription_id`:
 * that column is owned by the DoubleScale Subscriptions add-on (Stripe-driven
 * billing) and is actively written to, so the two generators must stay on
 * separate columns to keep their child invoices distinguishable.
 *
 * The column is inert when Pro is absent.
 *
 * @package DoubleScale\Modules\Documents
 */

namespace DoubleScale\Modules\Documents\Migrations;

defined( 'ABSPATH' ) || exit;

/**
 * SalesInvoiceTableRecurrenceColumn migration.
 */
class SalesInvoiceTableRecurrenceColumn {

	/**
	 * @return void
	 */
	public function run() {
		global $wpdb;

		$table = $wpdb->prefix . 'doublescale_sales_invoices';

		// phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery,WordPress.DB.DirectDatabaseQuery.NoCaching
		$exists = $wpdb->get_var( $wpdb->prepare( 'SHOW TABLES LIKE %s', $table ) );
		if ( $exists !== $table ) {
			return;
		}

		// phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery,WordPress.DB.DirectDatabaseQuery.NoCaching,WordPress.DB.PreparedSQL.InterpolatedNotPrepared
		$has_column = $wpdb->get_var( "SHOW COLUMNS FROM `{$table}` LIKE 'recurrence_id'" );
		if ( $has_column ) {
			return;
		}

		// `subscription_id` is only present on installs that have seen the
		// Subscriptions add-on's schema; append to the end when it is missing
		// rather than failing the ALTER outright.
		// phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery,WordPress.DB.DirectDatabaseQuery.NoCaching,WordPress.DB.PreparedSQL.InterpolatedNotPrepared
		$has_subscription_column = $wpdb->get_var( "SHOW COLUMNS FROM `{$table}` LIKE 'subscription_id'" );
		$position                = $has_subscription_column ? ' AFTER `subscription_id`' : '';

		// phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery,WordPress.DB.DirectDatabaseQuery.NoCaching,WordPress.DB.PreparedSQL.InterpolatedNotPrepared
		$wpdb->query(
			"ALTER TABLE `{$table}` ADD `recurrence_id` BIGINT(20) UNSIGNED NULL{$position}"
		);

		// phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery,WordPress.DB.DirectDatabaseQuery.NoCaching,WordPress.DB.PreparedSQL.InterpolatedNotPrepared
		$has_index = $wpdb->get_var( "SHOW INDEX FROM `{$table}` WHERE Key_name = 'idx_recurrence_id'" );
		if ( $has_index ) {
			return;
		}

		// phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery,WordPress.DB.DirectDatabaseQuery.NoCaching,WordPress.DB.PreparedSQL.InterpolatedNotPrepared
		$wpdb->query(
			"ALTER TABLE `{$table}` ADD KEY `idx_recurrence_id` (`recurrence_id`)"
		);
	}
}
