export const STORE_KEY = 'quillcrm/contacts';

// Action Types
export const FETCH_CONTACTS_START = 'FETCH_CONTACTS_START';
export const FETCH_CONTACTS_SUCCESS = 'FETCH_CONTACTS_SUCCESS';
export const FETCH_CONTACTS_ERROR = 'FETCH_CONTACTS_ERROR';

export const FETCH_CONTACT_START = 'FETCH_CONTACT_START';
export const FETCH_CONTACT_SUCCESS = 'FETCH_CONTACT_SUCCESS';
export const FETCH_CONTACT_ERROR = 'FETCH_CONTACT_ERROR';

export const CREATE_CONTACT_START = 'CREATE_CONTACT_START';
export const CREATE_CONTACT_SUCCESS = 'CREATE_CONTACT_SUCCESS';
export const CREATE_CONTACT_ERROR = 'CREATE_CONTACT_ERROR';

export const UPDATE_CONTACT_START = 'UPDATE_CONTACT_START';
export const UPDATE_CONTACT_SUCCESS = 'UPDATE_CONTACT_SUCCESS';
export const UPDATE_CONTACT_ERROR = 'UPDATE_CONTACT_ERROR';

export const DELETE_CONTACTS_START = 'DELETE_CONTACTS_START';
export const DELETE_CONTACTS_SUCCESS = 'DELETE_CONTACTS_SUCCESS';
export const DELETE_CONTACTS_ERROR = 'DELETE_CONTACTS_ERROR';

export const SET_FILTERS = 'SET_FILTERS';
export const SET_SEARCH_KEYWORDS = 'SET_SEARCH_KEYWORDS';
export const SET_SELECTED_IDS = 'SET_SELECTED_IDS';
export const CLEAR_SELECTED_IDS = 'CLEAR_SELECTED_IDS';

export const INVALIDATE_QUERY = 'INVALIDATE_QUERY';
export const SET_QUERY_CACHE = 'SET_QUERY_CACHE';
