/**
 * Constants
 */
const LAYOUT_CONSTANTS = {
	NODE_WIDTH: 380,
	ADD_STEP_WIDTH: 30,
	NODE_YES_NO_WIDTH: 60,
	START_X: 250,
	START_Y: 16,
	INCREMENT_Y: 250,
	/** Pixels between tab bar and top of trigger (used with setViewport) */
	VIEWPORT_TOP_GAP: 24,
	EDGE_STROKE_WIDTH: 2,
	CONDITION_EDGE_STROKE_WIDTH: 3,
	MINIMAP_HEIGHT: 120,
	MINIMAP_WIDTH: 200,
	POSITION_THRESHOLD: 2,
} as const;

const LAYOUT_CONSTANTS_VIEW_MODE = {
	NODE_WIDTH: 380,
	CONDITION_TO_BRANCH_SPACING: 200, // Increased spacing for view mode
} as const;

const SPACING_CONSTANTS = {
	BASE_WIDTH: 200,
	BRANCH_SPACING: 150,
	BASE_SPACING: 200,
	MERGE_SPACING: 120,
	NESTED_SPACING: 150,
	LEVEL_MULTIPLIER: 0.2,
	COMPLEXITY_PADDING: 40,
} as const;

const EDGE_STYLES = {
	DEFAULT: {
		stroke: '#D7D7DA',
		strokeWidth: LAYOUT_CONSTANTS.EDGE_STROKE_WIDTH,
		strokeLinecap: 'round' as const,
		strokeLinejoin: 'round' as const,
	},
	CONDITION: {
		stroke: '#D7D7DA',
		strokeWidth: LAYOUT_CONSTANTS.CONDITION_EDGE_STROKE_WIDTH,
	},
} as const;

export {
	LAYOUT_CONSTANTS,
	LAYOUT_CONSTANTS_VIEW_MODE,
	SPACING_CONSTANTS,
	EDGE_STYLES,
};
