export const leadsReportsData = [
  {
    key: "1",
    leadName: "Collins",
    companyName: "NovaWave LLC",
    companyLogo: "assets/img/icons/company-icon-01.svg",
    companyLocation: "Newyork, USA",
    phone: "+1 875455453",
    email: "robertson@example.com",
    leadStatus: "Closed",
    leadOwner: "Hendry",
    source: "Paid Social",
    createdDate: "25 Sep 2023, 01:22 pm",
  },
  {
    key: "2",
    leadName: "Konopelski",
    companyName: "BlueSky Industries",
    companyLogo: "assets/img/icons/company-icon-02.svg",
    companyLocation: "Winchester, KY",
    phone: "+1 989757485",
    email: "sharon@example.com",
    leadStatus: "Not Contacted",
    leadOwner: "Guillory",
    source: "Referrals",
    createdDate: "29 Sep 2023, 04:15 pm",
  },
  {
    key: "3",
    leadName: "Adams",
    companyName: "SilverHawk",
    companyLogo: "assets/img/icons/company-icon-03.svg",
    companyLocation: "Jametown, NY",
    phone: "+1 546555455",
    email: "vaughan12@example.com",
    leadStatus: "Closed",
    leadOwner: "Jami",
    source: "Campaigns",
    createdDate: "04 Oct 2023, 10:18 am",
  },
  {
    key: "4",
    leadName: "Schumm",
    companyName: "SummitPeak",
    companyLogo: "assets/img/icons/company-icon-04.svg",
    companyLocation: "Compton, RI",
    phone: "+1 454478787",
    email: "jessica13@example.com",
    leadStatus: "Contacted",
    leadOwner: "Theresa",
    source: "Google",
    createdDate: "17 Oct 2023, 03:31 pm",
  },
  {
    key: "5",
    leadName: "Wisozk",
    companyName: "RiverStone Ventur",
    companyLogo: "assets/img/icons/company-icon-05.svg",
    companyLocation: "Dayton, OH",
    phone: "+1 124547845",
    email: "caroltho3@example.com",
    leadStatus: "Closed",
    leadOwner: "Espinosa",
    source: "Paid Social",
    createdDate: "24 Oct 2023, 09:14 pm",
  },
  {
    key: "6",
    leadName: "Heller",
    companyName: "Bright Bridge Grp",
    companyLogo: "assets/img/icons/company-icon-06.svg",
    companyLocation: "Lafayette, LA",
    phone: "+1 478845447",
    email: "dawnmercha@example.com",
    leadStatus: "Closed",
    leadOwner: "Martin",
    source: "Referrals",
    createdDate: "08 Nov 2023, 09:56 am",
  },
  {
    key: "7",
    leadName: "Gutkowski",
    companyName: "CoastalStar Co.",
    companyLogo: "assets/img/icons/company-icon-07.svg",
    companyLocation: "Centerville, VA",
    phone: "+1 215544845",
    email: "rachel@example.com",
    leadStatus: "Closed",
    leadOwner: "Newell",
    source: "Campaigns",
    createdDate: "14 Nov 2023, 04:19 pm",
  },
  {
    key: "8",
    leadName: "Walter",
    companyName: "HarborView",
    companyLogo: "assets/img/icons/company-icon-08.svg",
    companyLocation: "Providence, RI",
    phone: "+1 121145471",
    email: "jonelle@example.com",
    leadStatus: "Closed",
    leadOwner: "Janet",
    source: "Google",
    createdDate: "23 Nov 2023, 11:14 pm",
  },
  {
    key: "9",
    leadName: "Hansen",
    companyName: "Golden Gate Ltd",
    companyLogo: "assets/img/icons/company-icon-09.svg",
    companyLocation: "Swayzee, IN",
    phone: "+1 321454789",
    email: "jonathan@example.com",
    leadStatus: "Closed",
    leadOwner: "Craig",
    source: "Paid Social",
    createdDate: "10 Dec 2023, 06:43 am",
  },
  {
    key: "10",
    leadName: "Leuschke",
    companyName: "Redwood Inc",
    companyLogo: "assets/img/icons/company-icon-10.svg",
    companyLocation: "Florida City, FL",
    phone: "+1 278907145",
    email: "brook@example.com",
    leadStatus: "Lost",
    leadOwner: "Daniel",
    source: "Referrals",
    createdDate: "10 Dec 2023, 06:43 am",
  },
];
