<?php
/**
 * REST controller for support mailboxes — the channels (departments) tickets
 * are routed through.
 *
 * Routes registered (namespace `doublescale/v1`):
 *
 *   GET    /support/mailboxes           List mailboxes (paginated).
 *   POST   /support/mailboxes           Create a mailbox.
 *   GET    /support/mailboxes/{id}      Read one (with `data` JSON decoded).
 *   PUT    /support/mailboxes/{id}      Update mutable fields.
 *   DELETE /support/mailboxes/{id}      Delete (NULLs tickets.mailbox_id via FK behaviour at the app layer).
 *
 * Mailboxes are pure-CRUD storage — no domain events, no service layer.
 * {@see MailboxModel::boot()} already enforces the two model invariants:
 * unique slug auto-generated from name/email on create, and the "only one
 * default at a time" rule on save. So this controller is thin: parse, validate,
 * persist, shape.
 *
 * The `data` LONGTEXT blob carries IMAP credentials and per-mailbox config.
 * Accessor/mutator on the model handle encode/decode, so the controller
 * receives/returns plain associative arrays.
 *
 * @since 1.0.0
 * @package DoubleScale\Modules\Support
 */

namespace DoubleScale\Modules\Support\Rest\Controllers;

defined( 'ABSPATH' ) || exit;

use DoubleScale\Core\Abstracts\RestController;
use DoubleScale\Core\UserRoles\Permissions;
use DoubleScale\Modules\Support\Models\MailboxModel;
use WP_Error;
use WP_REST_Request;
use WP_REST_Response;
use WP_REST_Server;

/**
 * RestMailboxController class.
 */
class RestMailboxController extends RestController {

	/**
	 * Route base. Combined with parent's `$namespace` gives
	 * `doublescale/v1/support/mailboxes`.
	 *
	 * @var string
	 */
	protected $rest_base = 'support/mailboxes';

	/**
	 * Columns the client may set / change directly. `slug` is generated by the
	 * model boot event when omitted, but the operator can supply one explicitly
	 * (validated client-side as URL-safe — the model retries on UNIQUE collision).
	 *
	 * @var string[]
	 */
	private const WRITABLE_FIELDS = array( 'slug', 'email', 'box_type', 'is_default', 'data' );

	/**
	 * Allowed `box_type` values. `web` mailboxes accept tickets via portal/forms;
	 * `email` mailboxes are IMAP-polled by Phase 3's EmailHandler.
	 *
	 * @var string[]
	 */
	private const BOX_TYPES = array( 'web', 'email' );

	/**
	 * Register routes.
	 *
	 * @return void
	 */
	public function register_routes() {
		register_rest_route(
			$this->namespace,
			'/' . $this->rest_base,
			array(
				array(
					'methods'             => WP_REST_Server::READABLE,
					'callback'            => array( $this, 'get_items' ),
					'permission_callback' => array( $this, 'get_items_permissions_check' ),
					'args'                => $this->get_collection_params(),
				),
				array(
					'methods'             => WP_REST_Server::CREATABLE,
					'callback'            => array( $this, 'create_item' ),
					'permission_callback' => array( $this, 'create_item_permissions_check' ),
				),
			)
		);

		register_rest_route(
			$this->namespace,
			'/' . $this->rest_base . '/(?P<id>[\d]+)',
			array(
				array(
					'methods'             => WP_REST_Server::READABLE,
					'callback'            => array( $this, 'get_item' ),
					'permission_callback' => array( $this, 'get_item_permissions_check' ),
				),
				array(
					'methods'             => WP_REST_Server::EDITABLE,
					'callback'            => array( $this, 'update_item' ),
					'permission_callback' => array( $this, 'update_item_permissions_check' ),
				),
				array(
					'methods'             => WP_REST_Server::DELETABLE,
					'callback'            => array( $this, 'delete_item' ),
					'permission_callback' => array( $this, 'delete_item_permissions_check' ),
				),
			)
		);
	}

	/**
	 * Standard collection params schema; called by core REST validation.
	 *
	 * @return array
	 */
	public function get_collection_params() {
		return array(
			'box_type' => array(
				'description' => __( 'Filter by mailbox channel type.', 'doublescale' ),
				'type'        => 'string',
				'enum'        => self::BOX_TYPES,
			),
			'search'   => array(
				'description' => __( 'Match on slug or email.', 'doublescale' ),
				'type'        => 'string',
			),
			'per_page' => array(
				'description' => __( 'Items per page (1-100).', 'doublescale' ),
				'type'        => 'integer',
				'default'     => 50,
				'minimum'     => 1,
				'maximum'     => 100,
			),
			'page'     => array(
				'description' => __( 'Page number.', 'doublescale' ),
				'type'        => 'integer',
				'default'     => 1,
				'minimum'     => 1,
			),
		);
	}

	// ---------------------------------------------------------------------
	// Endpoints
	// ---------------------------------------------------------------------

	/**
	 * List mailboxes.
	 *
	 * @param WP_REST_Request $request Request.
	 * @return WP_REST_Response|WP_Error
	 */
	public function get_items( $request ) {
		$disabled = $this->require_module( 'support' );
		if ( $disabled ) {
			return $disabled;
		}

		$query = MailboxModel::query();

		$box_type = $request->get_param( 'box_type' );
		if ( is_string( $box_type ) && in_array( $box_type, self::BOX_TYPES, true ) ) {
			$query->where( 'box_type', $box_type );
		}

		$search = $request->get_param( 'search' );
		if ( is_string( $search ) && '' !== trim( $search ) ) {
			$needle = '%' . str_replace( array( '%', '_' ), array( '\\%', '\\_' ), $search ) . '%';
			$query->where(
				function ( $q ) use ( $needle ) {
					$q->where( 'slug', 'LIKE', $needle )
						->orWhere( 'email', 'LIKE', $needle );
				}
			);
		}

		// Default first, then alpha by slug — gives admin UIs a stable order.
		$query->orderBy( 'is_default', 'desc' )->orderBy( 'slug', 'asc' );

		$per_page_raw = (int) $request->get_param( 'per_page' );
		$per_page     = max( 1, min( 100, $per_page_raw > 0 ? $per_page_raw : 50 ) );
		$page_raw     = (int) $request->get_param( 'page' );
		$page         = max( 1, $page_raw > 0 ? $page_raw : 1 );

		$paginator = $query->paginate( $per_page, array( '*' ), 'page', $page );

		$data = array();
		foreach ( $paginator->items() as $mailbox ) {
			$data[] = $this->shape_mailbox( $mailbox );
		}

		return new WP_REST_Response(
			array(
				'data' => $data,
				'meta' => array(
					'total'                => $paginator->total(),
					'per_page'             => $per_page,
					'current_page'         => $page,
					'last_page'            => max( 1, (int) ceil( $paginator->total() / $per_page ) ),
					// Sending identities the *current* user may bind to a mailbox
					// (capability-scoped). Sent alongside the list so the editor's
					// "Sender identity" picker needs no extra request. The same
					// scoping is re-applied on save (see validate()), so this is
					// the convenience half of a two-sided check.
					'available_identities' => $this->visible_identities_for_current_user(),
				),
			),
			200
		);
	}

	/**
	 * The SMTP connections the current user may pick as a mailbox sending
	 * identity. Thin wrapper over the SMTP module's single source of truth so
	 * the picker list and the save-time validation can't drift apart.
	 *
	 * @return array<int, array<string, mixed>>
	 */
	private function visible_identities_for_current_user(): array {
		if ( ! class_exists( '\DoubleScale\Modules\Smtp\Settings' ) ) {
			return array();
		}
		return \DoubleScale\Modules\Smtp\Settings::get_visible_connections_for_user( get_current_user_id() );
	}

	/**
	 * Get one mailbox by id.
	 *
	 * @param WP_REST_Request $request Request.
	 * @return WP_REST_Response|WP_Error
	 */
	public function get_item( $request ) {
		$disabled = $this->require_module( 'support' );
		if ( $disabled ) {
			return $disabled;
		}

		$mailbox = MailboxModel::find( (int) $request->get_param( 'id' ) );
		if ( ! $mailbox ) {
			return new WP_Error( 'not_found', __( 'Mailbox not found.', 'doublescale' ), array( 'status' => 404 ) );
		}

		return new WP_REST_Response( $this->shape_mailbox( $mailbox ), 200 );
	}

	/**
	 * Create a mailbox.
	 *
	 * `email` is required; everything else is optional. Slug auto-generates from
	 * `data.name` (falls back to email) via the model's `creating` boot event.
	 *
	 * @param WP_REST_Request $request Request.
	 * @return WP_REST_Response|WP_Error
	 */
	public function create_item( $request ) {
		$disabled = $this->require_module( 'support' );
		if ( $disabled ) {
			return $disabled;
		}

		$params = $request->get_json_params();
		if ( ! is_array( $params ) ) {
			$params = $request->get_params();
		}

		$validation = $this->validate( $params, true );
		if ( is_wp_error( $validation ) ) {
			return $validation;
		}

		$attributes = $this->extract_writable( $params );

		try {
			$mailbox = new MailboxModel();
			foreach ( $attributes as $key => $value ) {
				$mailbox->{$key} = $value;
			}
			$mailbox->save();
		} catch ( \Throwable $e ) {
			return new WP_Error( 'mailbox_create_failed', $e->getMessage(), array( 'status' => 500 ) );
		}

		return new WP_REST_Response( $this->shape_mailbox( $mailbox ), 201 );
	}

	/**
	 * Update a mailbox.
	 *
	 * Partial-update semantics — only the keys present in the request body are
	 * touched; everything else is left alone.
	 *
	 * @param WP_REST_Request $request Request.
	 * @return WP_REST_Response|WP_Error
	 */
	public function update_item( $request ) {
		$disabled = $this->require_module( 'support' );
		if ( $disabled ) {
			return $disabled;
		}

		$mailbox = MailboxModel::find( (int) $request->get_param( 'id' ) );
		if ( ! $mailbox ) {
			return new WP_Error( 'not_found', __( 'Mailbox not found.', 'doublescale' ), array( 'status' => 404 ) );
		}

		$params = $request->get_json_params();
		if ( ! is_array( $params ) ) {
			$params = $request->get_params();
		}
		unset( $params['id'] );

		$validation = $this->validate( $params, false );
		if ( is_wp_error( $validation ) ) {
			return $validation;
		}

		$attributes = $this->extract_writable( $params );

		try {
			foreach ( $attributes as $key => $value ) {
				$mailbox->{$key} = $value;
			}
			$mailbox->save();
		} catch ( \Throwable $e ) {
			return new WP_Error( 'mailbox_update_failed', $e->getMessage(), array( 'status' => 500 ) );
		}

		return new WP_REST_Response( $this->shape_mailbox( $mailbox ), 200 );
	}

	/**
	 * Delete a mailbox.
	 *
	 * Tickets that point at this mailbox keep their `mailbox_id` value (no app-
	 * level cascade). The Phase 5 admin UI surfaces orphan tickets via a
	 * "Mailbox: (deleted)" badge so operators can re-route manually.
	 *
	 * @param WP_REST_Request $request Request.
	 * @return WP_REST_Response|WP_Error
	 */
	public function delete_item( $request ) {
		$disabled = $this->require_module( 'support' );
		if ( $disabled ) {
			return $disabled;
		}

		$mailbox = MailboxModel::find( (int) $request->get_param( 'id' ) );
		if ( ! $mailbox ) {
			return new WP_Error( 'not_found', __( 'Mailbox not found.', 'doublescale' ), array( 'status' => 404 ) );
		}

		$mailbox->delete();
		return new WP_REST_Response( null, 204 );
	}

	// ---------------------------------------------------------------------
	// Permission checks
	// ---------------------------------------------------------------------

	/**
	 * Mailbox configuration is admin-tier — same gate as the ticket controller.
	 * Future hardening can split read vs. write caps once UserRoles ships the
	 * dedicated `support_agent` / `support_admin` roles.
	 *
	 * @param WP_REST_Request $request Unused — present for the WP REST contract.
	 * @return bool|WP_Error
	 */
	public function get_items_permissions_check( $request ) { // phpcs:ignore VariableAnalysis.CodeAnalysis.VariableAnalysis.UnusedVariable
		return $this->require_support_settings_access();
	}

	/**
	 * @param WP_REST_Request $request Unused — see {@see get_items_permissions_check()}.
	 * @return bool|WP_Error
	 */
	public function get_item_permissions_check( $request ) { // phpcs:ignore VariableAnalysis.CodeAnalysis.VariableAnalysis.UnusedVariable
		return $this->require_support_settings_access();
	}

	/**
	 * @param WP_REST_Request $request Unused — see {@see get_items_permissions_check()}.
	 * @return bool|WP_Error
	 */
	public function create_item_permissions_check( $request ) { // phpcs:ignore VariableAnalysis.CodeAnalysis.VariableAnalysis.UnusedVariable
		return $this->require_support_settings_access();
	}

	/**
	 * @param WP_REST_Request $request Unused — see {@see get_items_permissions_check()}.
	 * @return bool|WP_Error
	 */
	public function update_item_permissions_check( $request ) { // phpcs:ignore VariableAnalysis.CodeAnalysis.VariableAnalysis.UnusedVariable
		return $this->require_support_settings_access();
	}

	/**
	 * @param WP_REST_Request $request Unused — see {@see get_items_permissions_check()}.
	 * @return bool|WP_Error
	 */
	public function delete_item_permissions_check( $request ) { // phpcs:ignore VariableAnalysis.CodeAnalysis.VariableAnalysis.UnusedVariable
		return $this->require_support_settings_access();
	}

	// ---------------------------------------------------------------------
	// Internals
	// ---------------------------------------------------------------------

	/**
	 * Validate a request payload.
	 *
	 * `$is_create` flips two behaviours: (a) `email` becomes mandatory, since the
	 * model can't auto-generate it, and (b) we tolerate the absence of every
	 * other field. Updates allow partial bodies — only validate keys that are
	 * actually present.
	 *
	 * @param array $params    Request body.
	 * @param bool  $is_create True for POST, false for PUT.
	 * @return true|WP_Error
	 */
	private function validate( array $params, bool $is_create ) {
		if ( $is_create ) {
			if ( empty( $params['email'] ) || ! is_email( (string) $params['email'] ) ) {
				return new WP_Error( 'invalid_email', __( 'A valid mailbox email is required.', 'doublescale' ), array( 'status' => 400 ) );
			}
		} elseif ( isset( $params['email'] ) && ! is_email( (string) $params['email'] ) ) {
			return new WP_Error( 'invalid_email', __( 'Provided email is not valid.', 'doublescale' ), array( 'status' => 400 ) );
		}

		if ( isset( $params['box_type'] ) && ! in_array( $params['box_type'], self::BOX_TYPES, true ) ) {
			return new WP_Error(
				'invalid_box_type',
				/* translators: %s — allowed comma-separated values. */
				sprintf( __( 'Invalid box_type. Allowed: %s.', 'doublescale' ), implode( ', ', self::BOX_TYPES ) ),
				array( 'status' => 400 )
			);
		}

		if ( isset( $params['data'] ) && ! is_array( $params['data'] ) ) {
			return new WP_Error( 'invalid_data', __( 'The data field must be an object.', 'doublescale' ), array( 'status' => 400 ) );
		}

		$identity_error = $this->validate_identity( $params );
		if ( is_wp_error( $identity_error ) ) {
			return $identity_error;
		}

		return true;
	}

	/**
	 * Enforce that a submitted sending-identity `connection_id` is one the
	 * current user is actually allowed to bind.
	 *
	 * This is the *enforcement* half of the picker (the list endpoint only
	 * *offers* visible connections). Without this server-side check a Sales Rep
	 * could POST an arbitrary `data.identity.connection_id` — e.g. a colleague's
	 * personal address or an org address — and route a mailbox to send *as* an
	 * identity they aren't entitled to. We re-derive the allowed set from the
	 * same SMTP source the picker uses and reject anything outside it.
	 *
	 * An empty / absent identity is allowed (a mailbox may have no identity yet;
	 * outbound then skip-sends + logs — see EmailNotifications).
	 *
	 * @param array $params Request body.
	 * @return true|WP_Error
	 */
	private function validate_identity( array $params ) {
		if ( ! isset( $params['data'] ) || ! is_array( $params['data'] ) ) {
			return true;
		}
		$identity = $params['data']['identity'] ?? null;
		if ( empty( $identity ) || ! is_array( $identity ) ) {
			return true; // No identity submitted — allowed (skip-send until set).
		}

		$connection_id = isset( $identity['connection_id'] ) ? (string) $identity['connection_id'] : '';
		if ( '' === $connection_id ) {
			return true; // Explicitly cleared — allowed.
		}

		$allowed_ids = array();
		if ( class_exists( '\DoubleScale\Modules\Smtp\Settings' ) ) {
			foreach ( \DoubleScale\Modules\Smtp\Settings::get_visible_connections_for_user( get_current_user_id() ) as $conn ) {
				$allowed_ids[] = (string) $conn['connection_id'];
			}
		}

		if ( ! in_array( $connection_id, $allowed_ids, true ) ) {
			return new WP_Error(
				'identity_not_allowed',
				__( 'You are not allowed to use the selected sending identity for this mailbox.', 'doublescale' ),
				array( 'status' => 403 )
			);
		}

		return true;
	}

	/**
	 * Filter a request body down to writable columns. Anything else is dropped
	 * — defends against mass-assignment of timestamps / id / etc.
	 *
	 * @param array $params Raw request body.
	 * @return array
	 */
	private function extract_writable( array $params ): array {
		$out = array();
		foreach ( self::WRITABLE_FIELDS as $field ) {
			if ( array_key_exists( $field, $params ) ) {
				$out[ $field ] = $params[ $field ];
			}
		}

		if ( isset( $out['is_default'] ) ) {
			$out['is_default'] = (bool) $out['is_default'] ? 1 : 0;
		}
		if ( isset( $out['email'] ) ) {
			$out['email'] = strtolower( trim( (string) $out['email'] ) );
		}
		if ( isset( $out['slug'] ) ) {
			$out['slug'] = sanitize_title( (string) $out['slug'] );
		}

		return $out;
	}

	/**
	 * Shape a MailboxModel into the REST response shape.
	 *
	 * `data` returns as a JSON object (associative array) — the model's
	 * accessor already handles decoding. An empty mailbox emits `{}`, not `[]`,
	 * by coercing to stdClass when the array is empty so the JSON shape stays
	 * stable for TypeScript consumers.
	 *
	 * @param MailboxModel $mailbox Mailbox row.
	 * @return array
	 */
	private function shape_mailbox( MailboxModel $mailbox ): array {
		$data = $mailbox->data;
		if ( ! is_array( $data ) ) {
			$data = array();
		}

		return array(
			'id'         => (int) $mailbox->id,
			'slug'       => (string) $mailbox->slug,
			'email'      => (string) $mailbox->email,
			'box_type'   => (string) $mailbox->box_type,
			'is_default' => (bool) $mailbox->is_default,
			'name'       => (string) $mailbox->name,
			'data'       => empty( $data ) ? new \stdClass() : $data,
			'created_at' => $mailbox->created_at ? (string) $mailbox->created_at : null,
			'updated_at' => $mailbox->updated_at ? (string) $mailbox->updated_at : null,
		);
	}

	/**
	 * Baseline access guard. Mailboxes are managed from the Support Settings
	 * page, so this mirrors that page's gate: Administrators, CRM Managers, and
	 * the support roles (Support Manager / Support Agent). Sales Manager / Sales
	 * Rep are excluded — mailbox configuration is not a sales concern.
	 *
	 * @return bool|WP_Error
	 */
	private function require_support_settings_access() {
		if ( Permissions::can_access_support_settings() ) {
			return true;
		}
		return new WP_Error( 'not_allowed', __( 'You do not have permission to access support mailboxes.', 'doublescale' ), array( 'status' => 403 ) );
	}
}
