<?php
/**
 * Helpers for REST route registration tests.
 *
 * @package DoubleScale\Pro\Tests
 */

defined( 'ABSPATH' ) || exit;

/**
 * Clear the stub registry populated by {@see register_rest_route()}.
 */
function doublescale_rest_reset_route_registry(): void {
	$GLOBALS['__doublescale_phpunit_rest_registrations'] = array();
}

/**
 * Load short-name => FQCN map generated by tools/phpunit/build-rest-controller-manifest.php.
 *
 * @return array<string, string>|null
 */
function doublescale_rest_load_controller_fqcn_map( string $plugin_root ): ?array {
	$path = $plugin_root . '/phpunit/data/rest-controller-fqcn-map.json';
	if ( ! is_file( $path ) ) {
		return null;
	}
	$data = json_decode( (string) file_get_contents( $path ), true );
	return is_array( $data ) ? $data : null;
}

/**
 * FQCN for a controller short name (from committed map).
 */
function doublescale_rest_controller_fqcn_from_map( string $plugin_root, string $short_class ): ?string {
	$map = doublescale_rest_load_controller_fqcn_map( $plugin_root );
	if ( null === $map ) {
		return null;
	}
	return $map[ $short_class ] ?? null;
}

/**
 * Normalize the third argument of register_rest_route into a list of endpoint configs.
 *
 * @param array<string, mixed> $args
 * @return array<int, array<string, mixed>>
 */
function doublescale_rest_flatten_endpoint_configs( array $args ): array {
	if ( isset( $args['methods'], $args['callback'] ) ) {
		return array( $args );
	}

	$out = array();
	foreach ( $args as $key => $item ) {
		if ( 'args' === $key || 'schema' === $key ) {
			continue;
		}
		if ( is_array( $item ) && isset( $item['methods'], $item['callback'] ) ) {
			$out[] = $item;
		}
	}
	return $out;
}

/**
 * @return array<int, array{namespace: string, route: string, methods: mixed, callback: callable|array|string, permission: callable|array|string}>
 */
function doublescale_rest_collect_flat_endpoints(): array {
	$flat = array();
	foreach ( (array) $GLOBALS['__doublescale_phpunit_rest_registrations'] as $reg ) {
		if ( ! is_array( $reg ) || ! isset( $reg['namespace'], $reg['route'], $reg['args'] ) ) {
			continue;
		}
		$configs = doublescale_rest_flatten_endpoint_configs( $reg['args'] );
		foreach ( $configs as $cfg ) {
			$flat[] = array(
				'namespace'  => (string) $reg['namespace'],
				'route'      => (string) $reg['route'],
				'methods'    => $cfg['methods'] ?? null,
				'callback'   => $cfg['callback'] ?? null,
				'permission' => $cfg['permission_callback'] ?? null,
			);
		}
	}
	return $flat;
}
