<?php

/**
 * Abstract Send Message Action
 * Base class for all message sending actions (Email, SMS, WhatsApp)
 *
 * This class consolidates the common logic for sending messages across all channels:
 * - Template retrieval from step settings (templates created by model events)
 * - Tracking record creation
 * - Campaign infrastructure reuse
 * - Error handling and logging
 * - Validation patterns
 *
 * Child classes only need to implement channel-specific behavior.
 *
 * @since 1.0.0
 * @package QuillCRM
 */

namespace QuillCRM\Abstracts;

use QuillCRM\Models\Automation_Model;
use QuillCRM\Models\Automation_Step_Model;
use QuillCRM\Models\Automation_Contact_Model;
use QuillCRM\Models\Campaign_Model;
use QuillCRM\Models\Communication_Tracking_Model;
use QuillCRM\Models\Contact_Model;
use QuillCRM\Models\Template_Model;
use QuillCRM\Constants\Message_Source_Types;
use QuillCRM\Constants\Message_Direction;
use QuillCRM\Constants\Tracking_Status;
use QuillCRM\Utils;

/**
 * Abstract_Send_Message class
 */
abstract class Abstract_Send_Message extends Action {




	/**
	 * Source - all message actions are of type 'message'
	 *
	 * @var string
	 */
	public $source = 'message';

	/**
	 * Get the channel type (email, sms, whatsapp)
	 * Used for template creation, tracking, and campaign type
	 *
	 * @return string
	 */
	abstract protected function get_channel_type();

	/**
	 * Get the tracking mode constant
	 *
	 * @return int Communication_Tracking_Model::MODE_EMAIL, MODE_SMS, or MODE_WHATSAPP
	 */
	abstract protected function get_tracking_mode();

	/**
	 * Get the recipient field from contact (email or phone)
	 *
	 * @param Contact_Model $contact Contact Model.
	 * @return string|null
	 */
	abstract protected function get_recipient( Contact_Model $contact);

	/**
	 * Validate the recipient field
	 *
	 * @param Contact_Model $contact Contact Model.
	 * @return array|null Returns array with status/message if invalid, null if valid
	 */
	abstract protected function validate_recipient( Contact_Model $contact);

	/**
	 * Get the processing instance for this channel
	 * Returns Email_Processing, SMS_Processing, or WhatsApp_Processing instance
	 *
	 * @return object
	 */
	abstract protected function get_processing_instance();

	/**
	 * Get the channel name for logging (Email, SMS, WhatsApp)
	 *
	 * @return string
	 */
	abstract protected function get_channel_name();

	/**
	 * Process Action
	 * Consolidated logic for all message sending actions
	 *
	 * @since 1.0.0
	 *
	 * @param Automation_Model         $automation Automation Model.
	 * @param Automation_Step_Model    $step Automation Step Model.
	 * @param Automation_Contact_Model $automation_contact Automation Contact Model.
	 *
	 * @return bool|array True on success, false or array with status on failure
	 */
	public function process_action( Automation_Model $automation, Automation_Step_Model $step, Automation_Contact_Model $automation_contact ) {
		try {
			$contact      = $automation_contact->contact;
			$channel_name = $this->get_channel_name();
			$channel_type = $this->get_channel_type();

			// Check if contact is subscribed to this channel
			if ( ! $contact->is_subscribed_to_channel( $channel_type ) ) {
				quillcrm_get_logger()->info(
					"Skipping {$channel_name} automation action - contact unsubscribed from {$channel_type}",
					array(
						'automation_id' => $automation->id,
						'contact_id'    => $contact->id,
						'code'          => "send_{$channel_type}_unsubscribed",
					)
				);
				return array(
					'success' => false,
					'message' => sprintf( __( 'Contact unsubscribed from %s', 'quillcrm' ), $channel_name ),
					'code'    => 'contact_unsubscribed',
				);
			}

			// 1. Validate recipient
			$recipient_error = $this->validate_recipient( $contact );
			if ( $recipient_error ) {
				quillcrm_get_logger()->warning(
					"Send {$channel_name} action: {$recipient_error['message']}",
					array(
						'automation_id' => $automation->id,
						'contact_id'    => $contact->id,
						'code'          => "send_{$channel_type}_no_recipient",
					)
				);
				return $recipient_error;
			}

		// 2. Channel subscription check already handled above by is_subscribed_to_channel()
		// No additional global status check needed since global status field was removed

		// 3. Get template from step settings
		// Two approaches: auto-generated templates (SMS/Email) vs pre-selected templates (WhatsApp)
		// - SMS/Email: template_ids array (auto-generated by model events)
		// - WhatsApp: template_id integer (user-selected, requires variables setup)
		$template_id = $step->get_setting( 'template_id' ); // Direct template selection (WhatsApp)
		if ( empty( $template_id ) ) {
			// Fallback to auto-generated templates (SMS/Email)
			$template_ids = $step->get_setting( 'template_ids', array() );
			if ( ! empty( $template_ids ) ) {
				$template_id = reset( $template_ids );
			}
		}

		if ( empty( $template_id ) ) {
			quillcrm_get_logger()->error(
				"Send {$channel_name} action: No template ID found in step settings",
				array(
					'automation_id' => $automation->id,
					'step_id'       => $step->id,
					'contact_id'    => $contact->id,
					'code'          => "send_{$channel_type}_no_template_id",
				)
			);
			throw new \Exception( "No template ID found for automation step {$step->id}" );
		}

		$template = Template_Model::find( $template_id );

		if ( ! $template ) {
			quillcrm_get_logger()->error(
				"Send {$channel_name} action: Template not found in database",
				array(
					'automation_id' => $automation->id,
					'step_id'       => $step->id,
					'template_id'   => $template_id,
					'contact_id'    => $contact->id,
					'code'          => "send_{$channel_type}_template_not_found",
				)
			);
			throw new \Exception( "Template {$template_id} not found" );
		}

	// 4. Create tracking record BEFORE sending (critical for analytics)
		try {
			$tracking = Communication_Tracking_Model::create(
				array(
					'contact_id'  => $contact->id,
					'template_id' => $template->id,
					'mode'        => $this->get_tracking_mode(),
					'direction'   => Message_Direction::OUTBOUND,
					'source_type' => Message_Source_Types::AUTOMATION,
					'source_id'   => $automation->id,
					'step_id'     => $step->id,
					'recipient'   => $this->get_recipient( $contact ),
					'status'      => Tracking_Status::PENDING,
					'hash_key'    => Utils::generate_hash_key(),
				)
			);
		} catch ( \Exception $e ) {
			quillcrm_get_logger()->error(
				"Send {$channel_name} action: Exception creating tracking record",
				array(
					'automation_id' => $automation->id,
					'step_id'       => $step->id,
					'contact_id'    => $contact->id,
					'template_id'   => $template->id,
					'error'         => $e->getMessage(),
					'code'          => "send_{$channel_type}_tracking_exception",
				)
			);
			throw new \Exception( "Failed to create tracking record: {$e->getMessage()}" );
		}

			// Validate tracking was created successfully
			if ( ! $tracking || ! $tracking->id || $tracking->id === 0 ) {
				quillcrm_get_logger()->error(
					"Send {$channel_name} action: Failed to create tracking record - invalid ID",
					array(
						'automation_id' => $automation->id,
						'step_id'       => $step->id,
						'contact_id'    => $contact->id,
						'template_id'   => $template->id,
						'tracking_id'   => $tracking ? $tracking->id : 'null',
						'code'          => "send_{$channel_type}_tracking_creation_failed",
					)
				);
				throw new \Exception( 'Failed to create tracking record in database - ID is invalid' );
			}

		// 5. Prepare channel-specific message data (e.g., WhatsApp variables, SMS/Email content)
		// This allows child classes to perform pre-send setup (storing meta, validation, etc.)
		try {
			$message_data = $this->prepare_message_data( $step, $contact, $tracking );
		} catch ( \Exception $e ) {
			quillcrm_get_logger()->error(
				"Send {$channel_name} action: Failed to prepare message data",
				array(
					'automation_id' => $automation->id,
					'step_id'       => $step->id,
					'contact_id'    => $contact->id,
					'error'         => $e->getMessage(),
					'code'          => "send_{$channel_type}_prepare_data_failed",
				)
			);
			throw $e;
		}

			// 6. Create dummy campaign for process_campaign_message() to work
			// This allows us to reuse 100% of existing campaign infrastructure
			$dummy_campaign         = new Campaign_Model(
				array(
					'id'       => $automation->id,
					'name'     => 'Automation: ' . $automation->name,
					'type'     => $channel_type,
					'settings' => array(),
				)
			);
			$dummy_campaign->exists = true; // Mark as existing to prevent save attempts

			// 7. REUSE EXISTING CAMPAIGN INFRASTRUCTURE
			// This gives us: merge tags, provider integration, tracking, etc.
			// Pass automation_contact instead of contact to support automation-specific merge tags
			$this->get_processing_instance()->process_campaign_message(
				$dummy_campaign,
				$automation_contact,
				$tracking
			);

		// 8. Check result and return
		// Validate tracking ID before refresh to avoid "No query results" error
		if ( ! $tracking->id || $tracking->id === 0 ) {
			quillcrm_get_logger()->error(
				"Send {$channel_name} action: Tracking record was not created properly",
				array(
					'automation_id' => $automation->id,
					'contact_id'    => $contact->id,
					'tracking_id'   => $tracking->id,
					'code'          => "send_{$channel_type}_invalid_tracking_id",
				)
			);
			throw new \Exception( 'Failed to create tracking record' );
		}

		// Refresh tracking record to get updated status
		try {
			$tracking->refresh();
		} catch ( \Exception $e ) {
			$tracking_id = $tracking->id;
			quillcrm_get_logger()->error(
				"Send {$channel_name} action: Failed to refresh tracking record",
				array(
					'automation_id' => $automation->id,
					'contact_id'    => $contact->id,
					'tracking_id'   => $tracking_id,
					'error'         => $e->getMessage(),
					'code'          => "send_{$channel_type}_refresh_failed",
				)
			);
			// Try to fetch the tracking record manually as fallback
			$tracking = Communication_Tracking_Model::find( $tracking_id );
			if ( ! $tracking ) {
				throw new \Exception( "Tracking record {$tracking_id} not found after send" );
			}
		}

		if ( $tracking->status === Tracking_Status::SENT ) {
			quillcrm_get_logger()->info(
				"Send {$channel_name} action: Message sent successfully",
				array(
					'automation_id' => $automation->id,
					'contact_id'    => $contact->id,
					'tracking_id'   => $tracking->id,
					'template_id'   => $template->id,
					'code'          => "send_{$channel_type}_success",
				)
			);
			return true;
		} else {
			quillcrm_get_logger()->error(
				"Send {$channel_name} action: Message sending failed",
				array(
					'automation_id' => $automation->id,
					'contact_id'    => $contact->id,
					'tracking_id'   => $tracking->id,
					'status'        => $tracking->status,
					'code'          => "send_{$channel_type}_failed",
				)
			);
			return false;
		}
		} catch ( \Exception $e ) {
			quillcrm_get_logger()->error(
				"Send {$this->get_channel_name()} action: Exception occurred",
				array(
					'automation_id' => $automation->id ?? 0,
					'contact_id'    => $automation_contact->contact->id ?? 0,
					'error'         => $e->getMessage(),
					'code'          => "send_{$this->get_channel_type()}_exception",
				)
			);
			return false;
		}
	}

	/**
	 * Prepare channel-specific message data for sending
	 *
	 * This method should be implemented by child classes to extract relevant message
	 * content (e.g., body for SMS, template_id and variables for WhatsApp) from
	 * the automation step settings and prepare it for the processing instance.
	 *
	 * For WhatsApp: Should extract template_id and template_variables, store them
	 * in tracking meta, and return prepared data.
	 *
	 * For SMS/Email: Should extract body/subject and return prepared data.
	 *
	 * @param Automation_Step_Model        $step     Automation Step Model.
	 * @param Contact_Model                $contact  Contact Model.
	 * @param Communication_Tracking_Model $tracking Communication Tracking Model.
	 * @return array Prepared message data (structure varies by channel).
	 * @throws \Exception If required message data is missing or invalid.
	 */
	abstract protected function prepare_message_data( Automation_Step_Model $step, Contact_Model $contact, Communication_Tracking_Model $tracking );
}
